# GolangCI-Lint settings
version: "2"
# Disable all linters and enable the required ones
linters:
  default: none

  # Supported linters: https://golangci-lint.run/usage/linters/
  enable:
    - asasalint
    - asciicheck
    - bidichk
    - bodyclose
    - containedctx
    - copyloopvar
    - decorder
    - dupl
    - dupword
    - durationcheck
    - errcheck
    - errchkjson
    - errname
    - errorlint
    - exptostd
    - fatcontext
    - forbidigo
    - forcetypeassert
    - ginkgolinter
    - gocheckcompilerdirectives
    - gochecknoinits
    - gochecksumtype
    - gocognit
    - goconst
    - gocritic
    - gocyclo
    - goprintffuncname
    - gosec
    - govet
    - grouper
    - iface
    - importas
    - ineffassign
    - interfacebloat
    - lll
    - loggercheck
    - makezero
    - mirror
    - misspell
    - musttag
    - nakedret
    - nestif
    - nilerr
    - nilnesserr
    - noctx
    - nolintlint
    - nosprintfhostport
    - prealloc
    - predeclared
    - reassign
    - rowserrcheck
    - sqlclosecheck
    - staticcheck
    - testableexamples
    - tparallel
    - unconvert
    - unparam
    - unused
    - usestdlibvars
    - usetesting
    - wastedassign
    - zerologlint

  # Specific linter settings
  settings:
    gocognit:
      # Minimal code complexity to report
      min-complexity: 16
    gocyclo:
      # Minimal code complexity to report
      min-complexity: 16
    misspell:
      # Correct spellings using locale preferences for US
      locale: US
    staticcheck:
      # Default list with custom silencing of:

      checks: [
          "all",
          # Disable the checks that staticcheck disables by default
          "-ST1000",
          "-ST1003",
          "-ST1016",
          "-ST1020",
          "-ST1021",
          "-ST1022",
          "-QF1008", # Omit embedded fields from selector expression.
        ]
  exclusions:
    rules:
      # Exclude gochecknoinits and gosec from running on tests files
      - path: _test\.go
        linters:
          - dupl
          - gochecknoinits
          - gosec
          - errcheck
          - gocognit
          - musttag
          - noctx
          - usestdlibvars
          - exhaustruct
          - copyloopvar
          - goconst
      - path: test/*
        linters:
          - gochecknoinits
          - gosec
          - gocognit
      # Exclude lll issues for long lines with go:generate
      - linters:
          - lll
        source: "^//go:generate "
    paths:
      - .go/pkg/mod
      - vendor-fork
      - internal/logreporter/api/loki

# Run options
run:
  # 10 minute timeout for analysis
  timeout: 10m

issues:
  # Disable maximum issues count per one linter
  max-issues-per-linter: 0

  # Disable maximum count of issues with the same text
  max-same-issues: 0
